### ISSUE TITLE
如何设置只能单选？

### ISSUE THREAD

**Issue by tantaiheng** [GzhiYi/cn-region-picker#3]
目前项目能实现多选，如何设置选中某个城市之后就自动收起。需要改源码还是有属性可以设置？

**Comment by GzhiYi** [comment]
## 木有单选的属性哦。

考虑了下，如果选中某个城市就自动收起的话，用户使用感受不会好。如果确实需要这样的需求，可以修改组件内：移除省份选择；做一下`cityStatus`的watch，做关闭弹窗的处理。再者可以尝试如果选择多个确定的时候在`on-pick-city`函数进行提示处理。

@tantaiheng

**Comment by tantaiheng** [comment]
1，需求是让用户选择所在地区，选择后就返回数据收起城市列表
2，现在下载git版本后 npm install，npm run dev之后 
一、首先会显示入下图所示
![image](https://user-images.githubusercontent.com/24400887/62668962-5ad0bf00-b9c0-11e9-93d6-d2602a7f4b1f.png)
二、鼠标移动到上去点击无法打开选择器
![image](https://user-images.githubusercontent.com/24400887/62669073-d894ca80-b9c0-11e9-8ad9-99d4dbba8ece.png)

**Comment by GzhiYi** [comment]
把index.html的这部分代码注释下就可以了。
![code](https://user-images.githubusercontent.com/21136420/62671834-e6e7e400-b9ca-11e9-9f79-27febed92e65.png)

**Comment by tantaiheng** [comment]
一直没得空回复，可以了。非常感谢！

**Comment by CJhuochai** [comment]
数据不是双向绑定啊,咋办

**Comment by GzhiYi** [comment]
@CJhuochai 在事件回调处修改data就可以了。

**Comment by CJhuochai** [comment]
你好，现在的问题是和父页面数据不能双向互通，回调里面可以解决数据传到父页面但是回显不了



---原始邮件---
发件人: "GzhiYi"<notifications@github.com&gt;
发送时间: 2021年1月15日(周五) 下午5:02
收件人: "GzhiYi/cn-region-picker"<cn-region-picker@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"CJhuochai"<2452019836@qq.com&gt;;
主题: Re: [GzhiYi/cn-region-picker] 如何设置只能单选？ (#3)




 
@CJhuochai 在事件回调处修改data就可以了。

**Comment by GzhiYi** [comment]
我测试了一下是可以正常使用的，可以提供更多的信息不？
