### ISSUE TITLE
地区显示不全 怎么改margin

### ISSUE THREAD

**Issue by lilingzhisunge** [GzhiYi/cn-region-picker#5]
![image](https://user-images.githubusercontent.com/47549443/71338800-297e1780-258c-11ea-80cc-409d57bff55f.png)

**Comment by GzhiYi** [comment]
https://github.com/GzhiYi/cn-region-picker/blob/b43807b75a22a60a14712de3a32ad6212bf194d8/src/components/picker.scss#L73
改这里可以，但看起来是屏幕太小了？

**Comment by GzhiYi** [comment]
可以直接把组件放到项目内自定义修改。我close啦～
